language: java
env:
  global:
    - # ^^ OSSRH_USERNAME
    - secure: "OUV/9k60ATqUia1EAZffb92pKcxdiH55VsMPZVItKDUKclcaQwMouZT9Br1cmx0nqtGwtQJbGQUOmkocYejBnQNOrD8R+C+tCzv4cewEy+mGr+plwmgRugpjN77YQvJ4FnjdEaYSWwAhfPF4u5xWEMEudyWSVhvVu8F9lLZ8OBarheSQDwk741Kf30AwdcF9bskrxqD1VHUZYzpqrCXZerHBifYp2ptWMYLl0EcOEp/xw+18G1/Sne81OpFb3VHt0HKZdXHGGsK+ifxlmSRCIlxLYXgDUG8J0XBh32/qmqFaoDJnohypyff7GQSZJRT6516xxFROhkmhbN3bSfxYoZ0d2prZldg0fHwmls+gJECF0l0u/oeFSX5dQp7ly5zbu1vx7/80CMQCuF8T940j8oA3tx8jUkTzxeDs6cKf6yWz75heG27jqp95MGjENlN0ZEVM0X45+1uP6fHbYOVyUUdDs0+RFIcE6lkRuQKX3lQmGoh6F3N3q5O000oqm+2d+lhjinW2uwyq5KMX806Jhah4XtQF1d+XfZcSaQrIe6OigUjgE0xZplGcI60R+7HGc+IdOc6o29fkomtMS1YRfLSaV0oWUJyhW2bUO/xg3DXXnbl/vcaVFDI0DlUkmLT0m9nt8HRux1WoZBo7bpVRuk4c0pw5qa0z0uw4hz9ZTkA="
    - # ^^ OSSRH_PASSWORD
    - secure: "pvo+9cwW7WWCAoJL5YjnEgJgZa5DJMpApANQhVLMk1pWS1BiqlaS7EqFLxGnXr/8YLg2Aeds2iPij6GxfWR9q/aBV9UKPklQZ3rn/cC8JppaXMyV19MK67rf5mZZkM5lGsGzz/A2VjKYs4YkUtUcEdZnhd2NVY0jMnztHdBYsEW/4veXjXMT+K/fcWWGJ+oQEDF5R9ipZmROBBoyIIUCgudfbUF1EDMBlZlPzBrOfiXg2IJWSTGab44LoR8NVt3VBTGW31FU/gMIcSbfA0njk8btjFW2bGRW6VARg7NAAKyag64em/K/wfD/Us/LelxguesbvPqn9bPe1mc7dSigwAmusDncb2u8UXsdqv/gEE0OWz2qSs/PPwbTQOc7U7bLLH6hiRQSbnvBiczZ/V6UQ/otwz8Uu3CpmXUEikhAY61P+wu8KBQ+n0F6YWaKKZ8OvUsdDN4bbhB6X3ZZBI3MMKhqhzw/AljwXeXox5pyrvvNzz7Uv7tvkmRF8CaZ/uImDvFjwgH3dRwBXkLbOU5SqtB5YtVtA1F0lOYJMhcER1sbE53RADoJX7BBCTiybqpUL8kGmeUcTLD8igY4NTypuGooqTQfCjMlOLVlQaeT2n0YqeMt/EskZY5rbB+YRLpCbZcwgGfQ/n7EMdMgXkCnwRrKtKgZ/xhDICWlCXW7DbM="
    - # ^^ GPG_KEY_NAME
    - secure: "h/CYhFpYBJx7BVoSBqD/0mr820FOK2wuim096ftlGT0LmC7wJkuhzG4SR82Wrp8DJY0qzPG0et60+MmdCsrFtHAokcqYY8mNV/U99DdN9YY8IjvEaBm7oyjWchLMO1PqzHWRuxZz6Ou12QJf1eDUEOeuM2WKtIwL4d0xbt8QIu+zTgKm0Uyli89sk0iiUaUTbLMSIRjwZrV6o3/cO+Qki88j0Ui/Px8dZz9+/VY/W5drPQOMpMCAXEgCHRKmG9lXtmPFaxjie5vjMSpyeEMJKfj6/pSBf+v2QRa5C1CeleHK1O9TfzpGzR4iIYNyaf+8czZTXbp74+KeXx60Te9jeO2GrmA1PPz/Z91xRljSqAdp/bNUUlKK9VoTDqsaQM+wqBHwtgw9O0elavschaSBjRtisQBAaIJ+18U77nHmh6rWIxxj+epr4EekaI6k4xI/WspP6gNqHu1+tugt3T3qsQjcs3n9o66+0H1/on0Td4Ubz//4T34SabdMfFdjB5IgKZxDbSuZV1kmYN5fTcMTSsT5m3+zEDkkP6oefF1JjynTAvcZHVitZ/usioxiykGRrBwh1wRR5Bw/NWlfYuxDn0pepXJcGhmAFxPEFKHIp0L5q52jZhI4kumDbaK4Ca5ThHaZ6ph14ogSaGG69OsqvjT1q0BZKT83NM4yIKI7nQk="
    - # ^^ GPG_PASSPHRASE
    - secure: "rblfwaE3QBj02himP9DiaJHF5211UjwEL3Aa2oJxIeWCNoG+zy/1BTymWO2hyLX1RpE1uwIgmYl6pstel6Gxzubu8z45eUOp5MNVyOHHKHXfLq0rR0ObJLKF7R6EZJ1Iqdn0/n2ysLOkBcFuVwEEEHdQ0mjCoIwh1ZoHlGg4YKRz9YZJQdU/OT+KdPYxjcj9wgAimqs7fymuFfroIfV0N/xEjC17janfcyJO6lNiS/hq+Q7cPeAVvgph1MZDrTaYMwp33jQgWMqjW/DPzlSjjySVZWeI+WXunhNH4jGR12MnS4h1gZG/+McZdLONuOz2EKMQ3isaYQheF/zjTWHiPirBVUMegz1ZCnDdX/6VjeEYxF3PVAcpipLWsTchcdIFmWmcPmF5Tz4ZgmYvAYjabsW+V3iWAmD6DQFcHTBKu4bZTyoexZq/QZ778Ee1K0JDKifzY1sYaxmKccdEjND4ruFb/8n60Ub0kEAjA2qyEv5t1pTtN+nmZ2K02KNORS/k5HnmFrPLrzAl68smP9FWHQr+jo5d7Wf2SYtfIzTR2jB2AFs+12mGSUBnjilzON4jI/LcTWQfVmPICjD+Jpddc/GOg75NGARsthPfdl0v06XVCedeGPOeYJmPJBlSN0vjBLwfSyaKYzfdLANKK8Qsbsd92Jlnx7vVgBAqnzi0Xhw="
jdk:
  - oraclejdk8
install: mvn clean install -P !ossrh -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U  --settings .travis/mvnsettings.xml
script: mvn verify -P !ossrh -B --settings .travis/mvnsettings.xml
deploy:
  - provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
      branch: develop
after_failure:
  - find . -size +1k -regex  ".*-reports/.*\.txt" -exec cat {} +
cache:
  directories:
    - ~/.m2/repository
notifications:
  email:
    on_success: never
    on_failure: never

